name: Terraform Plan & Apply

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed

env:
  AWS_REGION: eu-west-2

jobs:
  terraform:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download tfvars file from S3
        run: aws s3 cp s3://my-terraform-config-bucket-muna/terraform.tfvars terraform/terraform.tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 📐 Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: terraform

      - name: ✅ Terraform Lint (optional but recommended)
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: 🧪 Run TFLint
        run: tflint --init && tflint
        working-directory: terraform


      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: terraform
