name: Terraform Plan

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed

env:
  AWS_REGION: eu-west-2

jobs:
  terraform:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download tfvars file from S3
        run: aws s3 cp s3://my-terraform-config-bucket-muna/terraform.tfvars terraform/terraform.tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: find . -name '*.tf' -exec terraform fmt -check -diff {} +
        working-directory: terraform

      - name: Install and Run TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          echo "$PWD" >> $GITHUB_PATH
          tflint --init
          tflint --config=terraform/.tflint.hcl terraform/

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file="terraform.tfvars"
        working-directory: terraform

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan
          retention-days: 1


      - name: Summary
        run: echo "### ✅ Terraform Plan Complete" >> $GITHUB_STEP_SUMMARY
